classdef getCResponse < robotics.ros.Message
    %getCResponse MATLAB implementation of dynamics/getCResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'dynamics/getCResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '8fc6bee779dde8defe0f7a3be3a232ff' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        C
    end
    
    properties (Constant, Hidden)
        PropertyList = {'C'} % List of non-constant message properties
        ROSPropertyList = {'c'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = getCResponse(msg)
            %getCResponse Construct the message object getCResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function c = get.C(obj)
            %get.C Get the value for property C
            javaArray = obj.JavaMessage.getC;
            array = obj.readJavaArray(javaArray, 'double');
            c = double(array);
        end
        
        function set.C(obj, c)
            %set.C Set the value for property C
            if ~isvector(c) && isempty(c)
                % Allow empty [] input
                c = double.empty(0,1);
            end
            
            validateattributes(c, {'numeric'}, {'vector'}, 'getCResponse', 'C');
            
            javaArray = obj.JavaMessage.getC;
            array = obj.writeJavaArray(c, javaArray, 'double');
            obj.JavaMessage.setC(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.C = obj.C;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.C = strObj.C;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.C = obj.C;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.dynamics.getCResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.dynamics.getCResponse;
            obj.reload(strObj);
        end
    end
end
