classdef GroupState < robotics.ros.Message
    %GroupState MATLAB implementation of dynamic_reconfigure/GroupState
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'dynamic_reconfigure/GroupState' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'a2d87f51dc22930325041a2f8b1571f8' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Name
        State
        Id
        Parent
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Id', 'Name', 'Parent', 'State'} % List of non-constant message properties
        ROSPropertyList = {'id', 'name', 'parent', 'state'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = GroupState(msg)
            %GroupState Construct the message object GroupState
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function name = get.Name(obj)
            %get.Name Get the value for property Name
            name = char(obj.JavaMessage.getName);
        end
        
        function set.Name(obj, name)
            %set.Name Set the value for property Name
            name = convertStringsToChars(name);
            
            validateattributes(name, {'char', 'string'}, {}, 'GroupState', 'Name');
            
            obj.JavaMessage.setName(name);
        end
        
        function state = get.State(obj)
            %get.State Get the value for property State
            state = logical(obj.JavaMessage.getState);
        end
        
        function set.State(obj, state)
            %set.State Set the value for property State
            validateattributes(state, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'GroupState', 'State');
            
            obj.JavaMessage.setState(state);
        end
        
        function id = get.Id(obj)
            %get.Id Get the value for property Id
            id = int32(obj.JavaMessage.getId);
        end
        
        function set.Id(obj, id)
            %set.Id Set the value for property Id
            validateattributes(id, {'numeric'}, {'nonempty', 'scalar'}, 'GroupState', 'Id');
            
            obj.JavaMessage.setId(id);
        end
        
        function parent = get.Parent(obj)
            %get.Parent Get the value for property Parent
            parent = int32(obj.JavaMessage.getParent);
        end
        
        function set.Parent(obj, parent)
            %set.Parent Set the value for property Parent
            validateattributes(parent, {'numeric'}, {'nonempty', 'scalar'}, 'GroupState', 'Parent');
            
            obj.JavaMessage.setParent(parent);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Name = obj.Name;
            cpObj.State = obj.State;
            cpObj.Id = obj.Id;
            cpObj.Parent = obj.Parent;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Name = strObj.Name;
            obj.State = strObj.State;
            obj.Id = strObj.Id;
            obj.Parent = strObj.Parent;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Name = obj.Name;
            strObj.State = obj.State;
            strObj.Id = obj.Id;
            strObj.Parent = obj.Parent;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.dynamic_reconfigure.GroupState.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.dynamic_reconfigure.GroupState;
            obj.reload(strObj);
        end
    end
end
